AIC_URI: https://aicond.meerkat-dev.com/
AWS_KEY_PROFILE: meerkat-dev
BUILD_METHOD: codebuild
CODEBUILD_ENV_COMPUTE_TYPE: BUILD_GENERAL1_SMALL
CODEBUILD_ENV_TYPE: LINUX_CONTAINER
LOGIN_MODE: static
REGION: ap-northeast-2
REPOSITORY_TAGS:
- Key=Owner,Value=Meerkat
VERSION: 1.1
WORKSPACE_NAME: common-ws
